# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\face.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(556, 523)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_export = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export.setGeometry(QtCore.QRect(120, 167, 93, 41))
        self.btn_export.setObjectName("btn_export")
        self.btn_play = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play.setGeometry(QtCore.QRect(10, 167, 93, 41))
        self.btn_play.setObjectName("btn_play")
        self.graphicsview_pic = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsview_pic.setGeometry(QtCore.QRect(310, 11, 221, 201))
        self.graphicsview_pic.setObjectName("graphicsview_pic")
        self.graphicsview_plot = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsview_plot.setGeometry(QtCore.QRect(10, 220, 521, 251))
        self.graphicsview_plot.setObjectName("graphicsview_plot")
        self.textinput_audio = QtWidgets.QLineEdit(self.centralwidget)
        self.textinput_audio.setGeometry(QtCore.QRect(70, 30, 221, 41))
        self.textinput_audio.setObjectName("textinput_audio")
        self.textinput_pic = QtWidgets.QLineEdit(self.centralwidget)
        self.textinput_pic.setGeometry(QtCore.QRect(70, 100, 221, 41))
        self.textinput_pic.setInputMask("")
        self.textinput_pic.setText("")
        self.textinput_pic.setObjectName("textinput_pic")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 30, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 100, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        #禁止拉伸窗口大小
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())

        self.retranslateUi(MainWindow)
        # MainWindow.setStyleSheet('''QWidget{background-color:rgb(226,226,226);}''')
        # self.graphicsview_plot.setStyleSheet('''QWidget{background-color:rgb(226,226,226);}''')
        self.graphicsview_plot.setStyleSheet("padding:0px;border:0px")
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_play, self.btn_export)
        MainWindow.setTabOrder(self.btn_export, self.graphicsview_pic)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image2Audio"))
        self.btn_export.setText(_translate("MainWindow", "expert"))
        self.btn_play.setText(_translate("MainWindow", "gen/play"))
        self.label.setText(_translate("MainWindow", "Audio:"))
        self.label_2.setText(_translate("MainWindow", "Image:"))
